import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { v2 as cloudinary } from "cloudinary";
// 1. Import the Enum generated by Prisma
import { KycStatus } from "@prisma/client";

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { 
      userId, 
      documentFront, 
      documentBack, 
      faceImage, 
      fullName, 
      fatherName, 
      docType, 
      docNum, 
      docExpiry 
    } = body;

    if (!userId) {
      return NextResponse.json({ error: "User ID is required" }, { status: 400 });
    }

    const uploadToCloudinary = async (base64: string, folder: string) => {
      if (!base64 || !base64.startsWith("data:image")) return base64; 
      
      const uploadRes = await cloudinary.uploader.upload(base64, {
        folder: `kyc/${userId}/${folder}`,
        resource_type: "image",
      });
      return uploadRes.secure_url;
    };

    // Upload images to Cloudinary
    const [frontUrl, backUrl, faceUrl] = await Promise.all([
      uploadToCloudinary(documentFront, "documents"),
      uploadToCloudinary(documentBack, "documents"),
      uploadToCloudinary(faceImage, "faces"),
    ]);

    // 2. Explicitly type the data object to satisfy Prisma's upsert requirements
    const kycData = {
      userId: userId,
      fullName: fullName,
      fatherName: fatherName,
      documentType: docType,
      documentNumber: docNum,
      documentExpiry: docExpiry ? new Date(docExpiry) : null,
      documentFront: frontUrl,
      documentBack: backUrl,
      faceImage: faceUrl,
      // 3. Use the Enum value instead of a raw string
      status: KycStatus.PENDING,
    };

    const res = await prisma.kYC.upsert({
      where: { userId: userId },
      update: kycData,
      create: kycData,
    });

    return NextResponse.json({ success: true, data: res });
  } catch (error: any) {
    console.error("KYC Error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to process KYC" }, 
      { status: 500 }
    );
  }
}